[project]
name = "mediaexplorer-ls"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.21.0",
    "litestar[standard,sqlalchemy]>=2.18.0",
    "requests>=2.32.5",
]
